services:

  config-server:
    build: ./config-server
    ports:
      - "8888:8888"

  discovery-service:
    build: ./discovery-service
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888

  gem-db:
    image: postgres:17-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: gemdb
      POSTGRES_USER: gem
      POSTGRES_PASSWORD: gem123
    volumes:
      - gem-data:/var/lib/postgresql/data

  dealer-db:
    image: postgres:17-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: dealerdb
      POSTGRES_USER: dealer
      POSTGRES_PASSWORD: dealer123
    volumes:
      - dealer-data:/var/lib/postgresql/data

  trade-db:
    image: postgres:17-alpine
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: tradedb
      POSTGRES_USER: trade
      POSTGRES_PASSWORD: trade123
    volumes:
      - trade-data:/var/lib/postgresql/data

  gem-service:
    build: ./gem-service
    ports:
      - "8081:8081"
    depends_on:
      - gem-db
      - discovery-service
      - config-server
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      SPRING_DATASOURCE_URL: jdbc:postgresql://gem-db:5432/gemdb
      SPRING_DATASOURCE_USERNAME: gem
      SPRING_DATASOURCE_PASSWORD: gem123

  dealer-service:
    build: ./dealer-service
    ports:
      - "8082:8082"
    depends_on:
      - dealer-db
      - discovery-service
      - config-server
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      SPRING_DATASOURCE_URL: jdbc:postgresql://dealer-db:5432/dealerdb
      SPRING_DATASOURCE_USERNAME: dealer
      SPRING_DATASOURCE_PASSWORD: dealer123

  trade-service:
    build: ./trade-service
    restart: on-failure
    ports:
      - "8083:8083"
    depends_on:
      - trade-db
      - discovery-service
      - config-server
      - gem-service
      - dealer-service
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888
      SPRING_DATASOURCE_URL: jdbc:postgresql://trade-db:5432/tradedb
      SPRING_DATASOURCE_USERNAME: trade
      SPRING_DATASOURCE_PASSWORD: trade123

  gateway-service:
    build: ./gateway-service
    ports:
      - "8088:8088"
    depends_on:
      - discovery-service
      - config-server
    environment:
      SPRING_CONFIG_IMPORT: optional:configserver:http://config-server:8888

  keycloak:
    image: docker.io/keycloak/keycloak:25.0.0
    command: start-dev --import-realm --health-enabled=true
    ports:
      - "9001:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json

volumes:
  gem-data:
  dealer-data:
  trade-data: