services:
  discovery-service:
    build: ./discovery-service
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]


  gem-db:
    image: postgres:17-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: gemdb
      POSTGRES_USER: gem
      POSTGRES_PASSWORD: gem123
    volumes:
      - gem-data:/var/lib/postgresql/data

  dealer-db:
    image: postgres:17-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: dealerdb
      POSTGRES_USER: dealer
      POSTGRES_PASSWORD: dealer123
    volumes:
      - dealer-data:/var/lib/postgresql/data


  trade-db:
    image: postgres:17-alpine
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: tradedb
      POSTGRES_USER: trade
      POSTGRES_PASSWORD: trade123
    volumes:
      - trade-data:/var/lib/postgresql/data

  gem-service:
    build: ./gem-service
    ports:
      - "8081:8081"
    depends_on:
      - gem-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://gem-db:5432/gemdb
      SPRING_DATASOURCE_USERNAME: gem
      SPRING_DATASOURCE_PASSWORD: gem123


  dealer-service:
    build: ./dealer-service
    ports:
      - "8082:8082"
    depends_on:
      - dealer-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dealer-db:5432/dealerdb
      SPRING_DATASOURCE_USERNAME: dealer
      SPRING_DATASOURCE_PASSWORD: dealer123


  trade-service:
    build: ./trade-service
    ports:
      - "8083:8083"
    depends_on:
      - trade-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://trade-db:5432/tradedb
      SPRING_DATASOURCE_USERNAME: trade
      SPRING_DATASOURCE_PASSWORD: trade123


volumes:
  gem-data:
  dealer-data:
  trade-data:
