server:
  port: 8083

spring:
  application:
    name: trade-service
  datasource:
    url: jdbc:postgresql://localhost:5437/tradedb
    username: trade
    password: trade123
  jpa:
    hibernate:
      ddl-auto: update

gem:
  service:
    url: http://localhost:8081

dealer:
  service:
    url: http://localhost:8082

trade:
  service:
    url: http://localhost:8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true