server:
  port: 8081

spring:
  application:
    name: gem-trading
  datasource:
    url: jdbc:postgresql://localhost:5433/gemdb
    username: gem
    password: gem123
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
